$:.unshift(File.dirname(__FILE__) + '/../../lib')
require 'cucumber/rake/task'

  Cucumber::Rake::Task.new(:headless) do |t|
    t.profile = "default"
  end

  Cucumber::Rake::Task.new(:selenium) do |t|
    t.profile = "selenium"
  end
